version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    ports: 
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=urlshortener
  
  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/apps/auth-service/main.js
      "
  url-service:
    build:
      context: .
      dockerfile: ./apps/url-service/Dockerfile
    ports:
      - '3002:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/apps/url-service/main.js
      "