global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3000'] 

  - job_name: 'url-service'
    static_configs:
      - targets: ['url-service:3000']
